apiVersion: v1
kind: Pod
metadata:
  name: temporary-pod-2
spec:
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: small-pvc-1
  containers:
  - name: busybox-container
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - mountPath: "/data"
      name: data-volume
    resources: {}